[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["lib"]
test = "contracts/test"
script = "contracts/script"
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Network settings
eth_rpc_url = "${ETH_RPC_URL}"

# Specify remappings if needed
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]