[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["lib"]
test = "contracts/test"
script = "contracts/script"
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"

# Optimizer settings
optimizer = true
optimizer_runs = 200



# Specify remappings if needed
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

# Sepolia configuration
[profile.sepolia]
eth_rpc_url = "${SEPOLIA_RPC_URL}"

# Mainnet configuration
[profile.mainnet]
eth_rpc_url = "${MAINNET_RPC_URL}"

# Local configuration
[profile.local]
eth_rpc_url = "http://localhost:8545"

# Etherscan configuration
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }